jobs:
# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  services:
    redis:
      image: redis
      ports:
      - 6379:6379
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: DotNetCoreInstaller@0
    inputs:
      version: '3.1.101'
  - script: cd scripts/aelf-node && bash start.sh
    displayName: 'Deploy a full node'
  - script: bash build.sh
    displayName: 'build and test'

