services:
  redis:
    image: redis
    ports:
      - 6379:6379
pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'aelf-sdk.java:$(build.buildId)'

steps:
  - script: cd scripts/aelf-node && bash start.sh
  - script: docker build -f Dockerfile -t $(imageName) .
    displayName: 'docker build'
