// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Transaction.proto

package io.aelf.proto;

public final class TransactionOuterClass {
  private TransactionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Transaction)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.Address From = 1;</code>
     */
    boolean hasFrom();
    /**
     * <code>.Address From = 1;</code>
     */
    io.aelf.proto.TransactionOuterClass.Address getFrom();
    /**
     * <code>.Address From = 1;</code>
     */
    io.aelf.proto.TransactionOuterClass.AddressOrBuilder getFromOrBuilder();

    /**
     * <code>.Address To = 2;</code>
     */
    boolean hasTo();
    /**
     * <code>.Address To = 2;</code>
     */
    io.aelf.proto.TransactionOuterClass.Address getTo();
    /**
     * <code>.Address To = 2;</code>
     */
    io.aelf.proto.TransactionOuterClass.AddressOrBuilder getToOrBuilder();

    /**
     * <code>int64 RefBlockNumber = 3;</code>
     */
    long getRefBlockNumber();

    /**
     * <code>bytes RefBlockPrefix = 4;</code>
     */
    com.google.protobuf.ByteString getRefBlockPrefix();

    /**
     * <code>string MethodName = 5;</code>
     */
    java.lang.String getMethodName();
    /**
     * <code>string MethodName = 5;</code>
     */
    com.google.protobuf.ByteString
        getMethodNameBytes();

    /**
     * <code>bytes Params = 6;</code>
     */
    com.google.protobuf.ByteString getParams();

    /**
     * <code>bytes Signature = 10000;</code>
     */
    com.google.protobuf.ByteString getSignature();
  }
  /**
   * Protobuf type {@code Transaction}
   */
  public  static final class Transaction extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Transaction)
      TransactionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Transaction.newBuilder() to construct.
    private Transaction(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Transaction() {
      refBlockPrefix_ = com.google.protobuf.ByteString.EMPTY;
      methodName_ = "";
      params_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Transaction(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.aelf.proto.TransactionOuterClass.Address.Builder subBuilder = null;
              if (from_ != null) {
                subBuilder = from_.toBuilder();
              }
              from_ = input.readMessage(io.aelf.proto.TransactionOuterClass.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(from_);
                from_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              io.aelf.proto.TransactionOuterClass.Address.Builder subBuilder = null;
              if (to_ != null) {
                subBuilder = to_.toBuilder();
              }
              to_ = input.readMessage(io.aelf.proto.TransactionOuterClass.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(to_);
                to_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              refBlockNumber_ = input.readInt64();
              break;
            }
            case 34: {

              refBlockPrefix_ = input.readBytes();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              methodName_ = s;
              break;
            }
            case 50: {

              params_ = input.readBytes();
              break;
            }
            case 80002: {

              signature_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.aelf.proto.TransactionOuterClass.internal_static_Transaction_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.aelf.proto.TransactionOuterClass.internal_static_Transaction_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.aelf.proto.TransactionOuterClass.Transaction.class, io.aelf.proto.TransactionOuterClass.Transaction.Builder.class);
    }

    public static final int FROM_FIELD_NUMBER = 1;
    private io.aelf.proto.TransactionOuterClass.Address from_;
    /**
     * <code>.Address From = 1;</code>
     */
    public boolean hasFrom() {
      return from_ != null;
    }
    /**
     * <code>.Address From = 1;</code>
     */
    public io.aelf.proto.TransactionOuterClass.Address getFrom() {
      return from_ == null ? io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance() : from_;
    }
    /**
     * <code>.Address From = 1;</code>
     */
    public io.aelf.proto.TransactionOuterClass.AddressOrBuilder getFromOrBuilder() {
      return getFrom();
    }

    public static final int TO_FIELD_NUMBER = 2;
    private io.aelf.proto.TransactionOuterClass.Address to_;
    /**
     * <code>.Address To = 2;</code>
     */
    public boolean hasTo() {
      return to_ != null;
    }
    /**
     * <code>.Address To = 2;</code>
     */
    public io.aelf.proto.TransactionOuterClass.Address getTo() {
      return to_ == null ? io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance() : to_;
    }
    /**
     * <code>.Address To = 2;</code>
     */
    public io.aelf.proto.TransactionOuterClass.AddressOrBuilder getToOrBuilder() {
      return getTo();
    }

    public static final int REFBLOCKNUMBER_FIELD_NUMBER = 3;
    private long refBlockNumber_;
    /**
     * <code>int64 RefBlockNumber = 3;</code>
     */
    public long getRefBlockNumber() {
      return refBlockNumber_;
    }

    public static final int REFBLOCKPREFIX_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString refBlockPrefix_;
    /**
     * <code>bytes RefBlockPrefix = 4;</code>
     */
    public com.google.protobuf.ByteString getRefBlockPrefix() {
      return refBlockPrefix_;
    }

    public static final int METHODNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object methodName_;
    /**
     * <code>string MethodName = 5;</code>
     */
    public java.lang.String getMethodName() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        methodName_ = s;
        return s;
      }
    }
    /**
     * <code>string MethodName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getMethodNameBytes() {
      java.lang.Object ref = methodName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        methodName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PARAMS_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString params_;
    /**
     * <code>bytes Params = 6;</code>
     */
    public com.google.protobuf.ByteString getParams() {
      return params_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 10000;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>bytes Signature = 10000;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (from_ != null) {
        output.writeMessage(1, getFrom());
      }
      if (to_ != null) {
        output.writeMessage(2, getTo());
      }
      if (refBlockNumber_ != 0L) {
        output.writeInt64(3, refBlockNumber_);
      }
      if (!refBlockPrefix_.isEmpty()) {
        output.writeBytes(4, refBlockPrefix_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, methodName_);
      }
      if (!params_.isEmpty()) {
        output.writeBytes(6, params_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(10000, signature_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (from_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFrom());
      }
      if (to_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getTo());
      }
      if (refBlockNumber_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, refBlockNumber_);
      }
      if (!refBlockPrefix_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, refBlockPrefix_);
      }
      if (!getMethodNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, methodName_);
      }
      if (!params_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, params_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(10000, signature_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.aelf.proto.TransactionOuterClass.Transaction)) {
        return super.equals(obj);
      }
      io.aelf.proto.TransactionOuterClass.Transaction other = (io.aelf.proto.TransactionOuterClass.Transaction) obj;

      if (hasFrom() != other.hasFrom()) return false;
      if (hasFrom()) {
        if (!getFrom()
            .equals(other.getFrom())) return false;
      }
      if (hasTo() != other.hasTo()) return false;
      if (hasTo()) {
        if (!getTo()
            .equals(other.getTo())) return false;
      }
      if (getRefBlockNumber()
          != other.getRefBlockNumber()) return false;
      if (!getRefBlockPrefix()
          .equals(other.getRefBlockPrefix())) return false;
      if (!getMethodName()
          .equals(other.getMethodName())) return false;
      if (!getParams()
          .equals(other.getParams())) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFrom()) {
        hash = (37 * hash) + FROM_FIELD_NUMBER;
        hash = (53 * hash) + getFrom().hashCode();
      }
      if (hasTo()) {
        hash = (37 * hash) + TO_FIELD_NUMBER;
        hash = (53 * hash) + getTo().hashCode();
      }
      hash = (37 * hash) + REFBLOCKNUMBER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getRefBlockNumber());
      hash = (37 * hash) + REFBLOCKPREFIX_FIELD_NUMBER;
      hash = (53 * hash) + getRefBlockPrefix().hashCode();
      hash = (37 * hash) + METHODNAME_FIELD_NUMBER;
      hash = (53 * hash) + getMethodName().hashCode();
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + getParams().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.aelf.proto.TransactionOuterClass.Transaction parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.aelf.proto.TransactionOuterClass.Transaction prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Transaction}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Transaction)
        io.aelf.proto.TransactionOuterClass.TransactionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.aelf.proto.TransactionOuterClass.internal_static_Transaction_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.aelf.proto.TransactionOuterClass.internal_static_Transaction_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.aelf.proto.TransactionOuterClass.Transaction.class, io.aelf.proto.TransactionOuterClass.Transaction.Builder.class);
      }

      // Construct using io.aelf.proto.TransactionOuterClass.Transaction.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fromBuilder_ == null) {
          from_ = null;
        } else {
          from_ = null;
          fromBuilder_ = null;
        }
        if (toBuilder_ == null) {
          to_ = null;
        } else {
          to_ = null;
          toBuilder_ = null;
        }
        refBlockNumber_ = 0L;

        refBlockPrefix_ = com.google.protobuf.ByteString.EMPTY;

        methodName_ = "";

        params_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.aelf.proto.TransactionOuterClass.internal_static_Transaction_descriptor;
      }

      @java.lang.Override
      public io.aelf.proto.TransactionOuterClass.Transaction getDefaultInstanceForType() {
        return io.aelf.proto.TransactionOuterClass.Transaction.getDefaultInstance();
      }

      @java.lang.Override
      public io.aelf.proto.TransactionOuterClass.Transaction build() {
        io.aelf.proto.TransactionOuterClass.Transaction result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.aelf.proto.TransactionOuterClass.Transaction buildPartial() {
        io.aelf.proto.TransactionOuterClass.Transaction result = new io.aelf.proto.TransactionOuterClass.Transaction(this);
        if (fromBuilder_ == null) {
          result.from_ = from_;
        } else {
          result.from_ = fromBuilder_.build();
        }
        if (toBuilder_ == null) {
          result.to_ = to_;
        } else {
          result.to_ = toBuilder_.build();
        }
        result.refBlockNumber_ = refBlockNumber_;
        result.refBlockPrefix_ = refBlockPrefix_;
        result.methodName_ = methodName_;
        result.params_ = params_;
        result.signature_ = signature_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.aelf.proto.TransactionOuterClass.Transaction) {
          return mergeFrom((io.aelf.proto.TransactionOuterClass.Transaction)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.aelf.proto.TransactionOuterClass.Transaction other) {
        if (other == io.aelf.proto.TransactionOuterClass.Transaction.getDefaultInstance()) return this;
        if (other.hasFrom()) {
          mergeFrom(other.getFrom());
        }
        if (other.hasTo()) {
          mergeTo(other.getTo());
        }
        if (other.getRefBlockNumber() != 0L) {
          setRefBlockNumber(other.getRefBlockNumber());
        }
        if (other.getRefBlockPrefix() != com.google.protobuf.ByteString.EMPTY) {
          setRefBlockPrefix(other.getRefBlockPrefix());
        }
        if (!other.getMethodName().isEmpty()) {
          methodName_ = other.methodName_;
          onChanged();
        }
        if (other.getParams() != com.google.protobuf.ByteString.EMPTY) {
          setParams(other.getParams());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.aelf.proto.TransactionOuterClass.Transaction parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.aelf.proto.TransactionOuterClass.Transaction) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private io.aelf.proto.TransactionOuterClass.Address from_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.aelf.proto.TransactionOuterClass.Address, io.aelf.proto.TransactionOuterClass.Address.Builder, io.aelf.proto.TransactionOuterClass.AddressOrBuilder> fromBuilder_;
      /**
       * <code>.Address From = 1;</code>
       */
      public boolean hasFrom() {
        return fromBuilder_ != null || from_ != null;
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public io.aelf.proto.TransactionOuterClass.Address getFrom() {
        if (fromBuilder_ == null) {
          return from_ == null ? io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance() : from_;
        } else {
          return fromBuilder_.getMessage();
        }
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public Builder setFrom(io.aelf.proto.TransactionOuterClass.Address value) {
        if (fromBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          from_ = value;
          onChanged();
        } else {
          fromBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public Builder setFrom(
          io.aelf.proto.TransactionOuterClass.Address.Builder builderForValue) {
        if (fromBuilder_ == null) {
          from_ = builderForValue.build();
          onChanged();
        } else {
          fromBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public Builder mergeFrom(io.aelf.proto.TransactionOuterClass.Address value) {
        if (fromBuilder_ == null) {
          if (from_ != null) {
            from_ =
              io.aelf.proto.TransactionOuterClass.Address.newBuilder(from_).mergeFrom(value).buildPartial();
          } else {
            from_ = value;
          }
          onChanged();
        } else {
          fromBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public Builder clearFrom() {
        if (fromBuilder_ == null) {
          from_ = null;
          onChanged();
        } else {
          from_ = null;
          fromBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public io.aelf.proto.TransactionOuterClass.Address.Builder getFromBuilder() {
        
        onChanged();
        return getFromFieldBuilder().getBuilder();
      }
      /**
       * <code>.Address From = 1;</code>
       */
      public io.aelf.proto.TransactionOuterClass.AddressOrBuilder getFromOrBuilder() {
        if (fromBuilder_ != null) {
          return fromBuilder_.getMessageOrBuilder();
        } else {
          return from_ == null ?
              io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance() : from_;
        }
      }
      /**
       * <code>.Address From = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.aelf.proto.TransactionOuterClass.Address, io.aelf.proto.TransactionOuterClass.Address.Builder, io.aelf.proto.TransactionOuterClass.AddressOrBuilder> 
          getFromFieldBuilder() {
        if (fromBuilder_ == null) {
          fromBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.aelf.proto.TransactionOuterClass.Address, io.aelf.proto.TransactionOuterClass.Address.Builder, io.aelf.proto.TransactionOuterClass.AddressOrBuilder>(
                  getFrom(),
                  getParentForChildren(),
                  isClean());
          from_ = null;
        }
        return fromBuilder_;
      }

      private io.aelf.proto.TransactionOuterClass.Address to_;
      private com.google.protobuf.SingleFieldBuilderV3<
          io.aelf.proto.TransactionOuterClass.Address, io.aelf.proto.TransactionOuterClass.Address.Builder, io.aelf.proto.TransactionOuterClass.AddressOrBuilder> toBuilder_;
      /**
       * <code>.Address To = 2;</code>
       */
      public boolean hasTo() {
        return toBuilder_ != null || to_ != null;
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public io.aelf.proto.TransactionOuterClass.Address getTo() {
        if (toBuilder_ == null) {
          return to_ == null ? io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance() : to_;
        } else {
          return toBuilder_.getMessage();
        }
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public Builder setTo(io.aelf.proto.TransactionOuterClass.Address value) {
        if (toBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          to_ = value;
          onChanged();
        } else {
          toBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public Builder setTo(
          io.aelf.proto.TransactionOuterClass.Address.Builder builderForValue) {
        if (toBuilder_ == null) {
          to_ = builderForValue.build();
          onChanged();
        } else {
          toBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public Builder mergeTo(io.aelf.proto.TransactionOuterClass.Address value) {
        if (toBuilder_ == null) {
          if (to_ != null) {
            to_ =
              io.aelf.proto.TransactionOuterClass.Address.newBuilder(to_).mergeFrom(value).buildPartial();
          } else {
            to_ = value;
          }
          onChanged();
        } else {
          toBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public Builder clearTo() {
        if (toBuilder_ == null) {
          to_ = null;
          onChanged();
        } else {
          to_ = null;
          toBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public io.aelf.proto.TransactionOuterClass.Address.Builder getToBuilder() {
        
        onChanged();
        return getToFieldBuilder().getBuilder();
      }
      /**
       * <code>.Address To = 2;</code>
       */
      public io.aelf.proto.TransactionOuterClass.AddressOrBuilder getToOrBuilder() {
        if (toBuilder_ != null) {
          return toBuilder_.getMessageOrBuilder();
        } else {
          return to_ == null ?
              io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance() : to_;
        }
      }
      /**
       * <code>.Address To = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          io.aelf.proto.TransactionOuterClass.Address, io.aelf.proto.TransactionOuterClass.Address.Builder, io.aelf.proto.TransactionOuterClass.AddressOrBuilder> 
          getToFieldBuilder() {
        if (toBuilder_ == null) {
          toBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              io.aelf.proto.TransactionOuterClass.Address, io.aelf.proto.TransactionOuterClass.Address.Builder, io.aelf.proto.TransactionOuterClass.AddressOrBuilder>(
                  getTo(),
                  getParentForChildren(),
                  isClean());
          to_ = null;
        }
        return toBuilder_;
      }

      private long refBlockNumber_ ;
      /**
       * <code>int64 RefBlockNumber = 3;</code>
       */
      public long getRefBlockNumber() {
        return refBlockNumber_;
      }
      /**
       * <code>int64 RefBlockNumber = 3;</code>
       */
      public Builder setRefBlockNumber(long value) {
        
        refBlockNumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 RefBlockNumber = 3;</code>
       */
      public Builder clearRefBlockNumber() {
        
        refBlockNumber_ = 0L;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString refBlockPrefix_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes RefBlockPrefix = 4;</code>
       */
      public com.google.protobuf.ByteString getRefBlockPrefix() {
        return refBlockPrefix_;
      }
      /**
       * <code>bytes RefBlockPrefix = 4;</code>
       */
      public Builder setRefBlockPrefix(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        refBlockPrefix_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes RefBlockPrefix = 4;</code>
       */
      public Builder clearRefBlockPrefix() {
        
        refBlockPrefix_ = getDefaultInstance().getRefBlockPrefix();
        onChanged();
        return this;
      }

      private java.lang.Object methodName_ = "";
      /**
       * <code>string MethodName = 5;</code>
       */
      public java.lang.String getMethodName() {
        java.lang.Object ref = methodName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          methodName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string MethodName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getMethodNameBytes() {
        java.lang.Object ref = methodName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          methodName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string MethodName = 5;</code>
       */
      public Builder setMethodName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        methodName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string MethodName = 5;</code>
       */
      public Builder clearMethodName() {
        
        methodName_ = getDefaultInstance().getMethodName();
        onChanged();
        return this;
      }
      /**
       * <code>string MethodName = 5;</code>
       */
      public Builder setMethodNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        methodName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString params_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Params = 6;</code>
       */
      public com.google.protobuf.ByteString getParams() {
        return params_;
      }
      /**
       * <code>bytes Params = 6;</code>
       */
      public Builder setParams(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        params_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Params = 6;</code>
       */
      public Builder clearParams() {
        
        params_ = getDefaultInstance().getParams();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes Signature = 10000;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <code>bytes Signature = 10000;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes Signature = 10000;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Transaction)
    }

    // @@protoc_insertion_point(class_scope:Transaction)
    private static final io.aelf.proto.TransactionOuterClass.Transaction DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.aelf.proto.TransactionOuterClass.Transaction();
    }

    public static io.aelf.proto.TransactionOuterClass.Transaction getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Transaction>
        PARSER = new com.google.protobuf.AbstractParser<Transaction>() {
      @java.lang.Override
      public Transaction parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Transaction(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Transaction> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Transaction> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.aelf.proto.TransactionOuterClass.Transaction getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue();
  }
  /**
   * Protobuf type {@code Address}
   */
  public  static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      value_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Address(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {

              value_ = input.readBytes();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.aelf.proto.TransactionOuterClass.internal_static_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.aelf.proto.TransactionOuterClass.internal_static_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.aelf.proto.TransactionOuterClass.Address.class, io.aelf.proto.TransactionOuterClass.Address.Builder.class);
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <code>bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!value_.isEmpty()) {
        output.writeBytes(1, value_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.aelf.proto.TransactionOuterClass.Address)) {
        return super.equals(obj);
      }
      io.aelf.proto.TransactionOuterClass.Address other = (io.aelf.proto.TransactionOuterClass.Address) obj;

      if (!getValue()
          .equals(other.getValue())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.aelf.proto.TransactionOuterClass.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.aelf.proto.TransactionOuterClass.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Address)
        io.aelf.proto.TransactionOuterClass.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.aelf.proto.TransactionOuterClass.internal_static_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.aelf.proto.TransactionOuterClass.internal_static_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.aelf.proto.TransactionOuterClass.Address.class, io.aelf.proto.TransactionOuterClass.Address.Builder.class);
      }

      // Construct using io.aelf.proto.TransactionOuterClass.Address.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.aelf.proto.TransactionOuterClass.internal_static_Address_descriptor;
      }

      @java.lang.Override
      public io.aelf.proto.TransactionOuterClass.Address getDefaultInstanceForType() {
        return io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance();
      }

      @java.lang.Override
      public io.aelf.proto.TransactionOuterClass.Address build() {
        io.aelf.proto.TransactionOuterClass.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.aelf.proto.TransactionOuterClass.Address buildPartial() {
        io.aelf.proto.TransactionOuterClass.Address result = new io.aelf.proto.TransactionOuterClass.Address(this);
        result.value_ = value_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.aelf.proto.TransactionOuterClass.Address) {
          return mergeFrom((io.aelf.proto.TransactionOuterClass.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.aelf.proto.TransactionOuterClass.Address other) {
        if (other == io.aelf.proto.TransactionOuterClass.Address.getDefaultInstance()) return this;
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.aelf.proto.TransactionOuterClass.Address parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.aelf.proto.TransactionOuterClass.Address) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <code>bytes value = 1;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Address)
    }

    // @@protoc_insertion_point(class_scope:Address)
    private static final io.aelf.proto.TransactionOuterClass.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.aelf.proto.TransactionOuterClass.Address();
    }

    public static io.aelf.proto.TransactionOuterClass.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Address(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.aelf.proto.TransactionOuterClass.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Transaction_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Transaction_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021Transaction.proto\"\243\001\n\013Transaction\022\026\n\004F" +
      "rom\030\001 \001(\0132\010.Address\022\024\n\002To\030\002 \001(\0132\010.Addres" +
      "s\022\026\n\016RefBlockNumber\030\003 \001(\003\022\026\n\016RefBlockPre" +
      "fix\030\004 \001(\014\022\022\n\nMethodName\030\005 \001(\t\022\016\n\006Params\030" +
      "\006 \001(\014\022\022\n\tSignature\030\220N \001(\014\"\030\n\007Address\022\r\n\005" +
      "value\030\001 \001(\014B\017\n\rio.aelf.protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Transaction_descriptor,
        new java.lang.String[] { "From", "To", "RefBlockNumber", "RefBlockPrefix", "MethodName", "Params", "Signature", });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
